version: "3"

services:
  pg:
    image: postgres:15
#    build: ...
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: otus
      POSTGRES_PASSWORD: otus12345
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
#    volumes:
#      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "shop", "-U", "otus" ]
      interval: 30s
      timeout: 60s
      retries: 5

#volumes:
#  db-data: